# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Continuum < Formula
  desc "Terminal-first context orchestration for AI-assisted development."
  homepage "https://github.com/simoneaveotti/continuum"
  version "0.6.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.6.8/ctx_0.6.8_darwin_amd64.tar.gz"
      sha256 "4574482a61f407cc34f95007f772616c60919d562317e55b7f66ccc9a465ec2e"

      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.6.8/ctx_0.6.8_darwin_arm64.tar.gz"
      sha256 "56a26f4ca73a8c15562912be9e0791be4aefac675ba2a62f35e3d55434481201"

      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.6.8/ctx_0.6.8_linux_amd64.tar.gz"
      sha256 "a302f34ac072344ec2a692a88dce2d2a03cca040190290ead85da38da59a631f"
      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.6.8/ctx_0.6.8_linux_arm64.tar.gz"
      sha256 "20501d18a0376f0e63b7e40cca82fe327e7dd984cdd7a5282545e73838f9237c"
      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
  end

  test do
    system "#{bin}/ctx", "--version"
  end
end
