# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Continuum < Formula
  desc "Terminal-first context orchestration for AI-assisted development."
  homepage "https://github.com/simoneaveotti/continuum"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.9.1/ctx_0.9.1_darwin_amd64.tar.gz"
      sha256 "e0a80445a62b3209923bdc1da35693e541f0511ec8c1872a371087bad40f94b8"

      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.9.1/ctx_0.9.1_darwin_arm64.tar.gz"
      sha256 "61964795c999b53bf4f48d93d99b296f87bcb0c2d2ed3a998bede6592e40c46a"

      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.9.1/ctx_0.9.1_linux_amd64.tar.gz"
      sha256 "01b9436bfded200bffb29dcfc1cdb37cf91bbe7c7f114ab5b0d8c5a105f20b86"
      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.9.1/ctx_0.9.1_linux_arm64.tar.gz"
      sha256 "6f582a239d7c94895b522691d3c1866626b0fe9efdb3a008a0f6f9b8244249b1"
      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
  end

  test do
    system "#{bin}/ctx", "--version"
  end
end
