# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Continuum < Formula
  desc "Terminal-first context orchestration for AI-assisted development."
  homepage "https://github.com/simoneaveotti/continuum"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.8.1/ctx_0.8.1_darwin_amd64.tar.gz"
      sha256 "90ec849074c02f59fdf93d838055d72a412c36ed1ba334e11d517c0aa370a017"

      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.8.1/ctx_0.8.1_darwin_arm64.tar.gz"
      sha256 "3bddbb70aba632ec4e9601837a1aa4624e8e7829dbbe01547c64161a85ad9e49"

      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.8.1/ctx_0.8.1_linux_amd64.tar.gz"
      sha256 "4f49ae60c34280d48dfdae30452d5b1dd10a78bf6c4eee1075f786399fd2640a"
      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simoneaveotti/continuum/releases/download/v0.8.1/ctx_0.8.1_linux_arm64.tar.gz"
      sha256 "9658637ba1e6b129bb31cccb31f73f4b19687a7e42bfdd6945a2221a6ae3f2ac"
      define_method(:install) do
        bin.install "ctx"
        pkgshare.install "templates"
      end
    end
  end

  test do
    system "#{bin}/ctx", "--version"
  end
end
